"""Core application utilities and configuration."""

from app.core.auth_config import AuthConfig, NoAuth, OAuthAuth, PasswordAuth
from app.core.config import NetSuiteConfig, Settings, get_netsuite_config, get_settings
from app.core.constants import (
    API_PREFIX,
    AUTH_INFO_PATH,
    AUTH_PATH,
    EXEMPT_PATHS,
    HEALTH_DETAILED_PATH,
    HEALTH_PATH,
    NETSUITE_ACCOUNT_HEADER,
    NETSUITE_API_VERSION_HEADER,
    NETSUITE_CONSUMER_KEY_HEADER,
    NETSUITE_CONSUMER_SECRET_HEADER,
    NETSUITE_DEFAULT_API_VERSION,
    NETSUITE_DEFAULT_APPLICATION_ID,
    NETSUITE_DEFAULT_RESTLET_TIMEOUT,
    NETSUITE_DEFAULT_SOAP_TIMEOUT,
    NETSUITE_DEPLOY_ID_HEADER,
    NETSUITE_EMAIL_HEADER,
    NETSUITE_PASSWORD_HEADER,
    NETSUITE_ROLE_HEADER,
    NETSUITE_SCRIPT_ID_HEADER,
    NETSUITE_TOKEN_ID_HEADER,
    NETSUITE_TOKEN_SECRET_HEADER,
)
from app.core.exceptions import (
    AuthenticationError,
    ConcurrencyError,
    NetSuiteError,
    NetSuitePermissionError,
    NetSuiteTimeoutError,
    PageBoundsError,
    RateLimitError,
    RecordNotFoundError,
    RESTletError,
    SOAPFaultError,
    ValidationError,
)
from app.core.logging import add_request_context, configure_logging, get_logger

__all__ = [
    "API_PREFIX",
    "AUTH_INFO_PATH",
    "AUTH_PATH",
    "EXEMPT_PATHS",
    "HEALTH_DETAILED_PATH",
    "HEALTH_PATH",
    "NETSUITE_ACCOUNT_HEADER",
    "NETSUITE_API_VERSION_HEADER",
    "NETSUITE_CONSUMER_KEY_HEADER",
    "NETSUITE_CONSUMER_SECRET_HEADER",
    "NETSUITE_DEFAULT_API_VERSION",
    "NETSUITE_DEFAULT_APPLICATION_ID",
    "NETSUITE_DEFAULT_RESTLET_TIMEOUT",
    "NETSUITE_DEFAULT_SOAP_TIMEOUT",
    "NETSUITE_DEPLOY_ID_HEADER",
    "NETSUITE_EMAIL_HEADER",
    "NETSUITE_PASSWORD_HEADER",
    "NETSUITE_ROLE_HEADER",
    "NETSUITE_SCRIPT_ID_HEADER",
    "NETSUITE_TOKEN_ID_HEADER",
    "NETSUITE_TOKEN_SECRET_HEADER",
    "AuthConfig",
    "AuthenticationError",
    "ConcurrencyError",
    "NetSuiteConfig",
    "NetSuiteError",
    "NetSuitePermissionError",
    "NetSuiteTimeoutError",
    "NoAuth",
    "OAuthAuth",
    "PageBoundsError",
    "PasswordAuth",
    "RESTletError",
    "RateLimitError",
    "RecordNotFoundError",
    "SOAPFaultError",
    "Settings",
    "ValidationError",
    "add_request_context",
    "configure_logging",
    "get_logger",
    "get_netsuite_config",
    "get_settings",
]
